### ISSUE TITLE
Add: ユーザ機能

### ISSUE THREAD

**Issue by Ayumu-O** [Ayumu-O/sample-app#1]
# 概要
deviseを用いてログイン機能を実装する。
ユーザ新規登録、編集、削除機能を実装する。
ユーザのメールアドレス、名前、パスワード情報を保持する。
簡易的なtop画面を作り、動作確認を行う。

# 要件
- gem deviseを使用する
- Userの登録、編集、削除を可能にする
- ログイン・ログアウトを可能にする
- UserマスタのカラムはER図（別途作成）を参照 #7
- UserマスタのカラムにNameカラムを追加
- 簡易的なtop画面からUserの登録、編集、削除、ログイン・ログアウトを実行できる

# ToDo
- [x] gem
  - [x] devise
- [x] migration
  - [x] User
- [x] model
  - [x] user model
  - [x] user test #6 
- [x] controller
  - [x] application controller
  - [x] users/registrations controller
  - [x] users/sessions controller
-  [x] view
   - [x] users/sessions view (new)  
   - [x] users/registrations view (new)  
   - [x] users/registrations view (edit)   
- [x] config
  - [x] route

**Comment by Ayumu-O** [comment]
【Rails】deviseを導入してみる - Qiita
https://qiita.com/Hal_mai/items/350c400e8763ce0487a3
